name: Testes

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Instalar
        run: pip install ".[dev]"

      - name: Testes unitários
        run: pytest -v
